[project]
name = "cookmate-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.2.0",
    "pandas>=2.3.3",

]

[tool.uv.sources]
cookmate-backend = { workspace = true }
cookmate-frontend = { workspace = true }
utils = { workspace = true }
torch = { index = "pytorch-cpu" }

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.uv.workspace]
members = ["src/cookmate/cookmate-frontend", "src/cookmate/cookmate-backend", "src/cookmate/utils"]


[tool.hatch.build.targets.wheel]
packages =  ["src/cookmate"]
